services:
  - type: web
    name: snapchat-app
    env: node
    region: oregon
    plan: free
    buildCommand: echo pre-built
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
